/*
 * Copyright (c) 2024. Khutaba Kiazim. All rights reserved.
 */
import {Roli} from "../../../utils/enums/Roli.js";
import {OrderStatus} from "../../../utils/zakazi/statusi_zakaza.js";

const isReceived = order => order?.order_status === OrderStatus.ReceivedByCourier;
const isAssignedTo = order => order?.order_status === OrderStatus.AssignedToCourier;
const isNotPosponed = order => order?.order_status !== OrderStatus.Postponed;

const available_for_admin_or_manager = (order) => {
    return ![OrderStatus.Waiting, OrderStatus.Accepted].includes(order?.order_status);
}

const available_for_storekeeper = (order) => {
    return ![OrderStatus.ReceivedByCourier].includes(order?.order_status);
}

function availabilityMap(
    comment,
    client_debt,
    order_bonuses,
    amount_to_pay,
    price,
    paid_total,
    received_at,
    issued_at,
    weight,
    price_list,
    service_price,
    wh_cell,
    amount_paid_cash,
    amount_paid_cashless,
    amount_paid_bonus,
    amount_deposited,
    photo_add,
    postpone_button,
    cancel_button,
    common_debt = true,
    client_debt_in_dp = true
) {
    return {
        comment,
        'client_debt': client_debt,
        order_bonuses,
        amount_to_pay,
        price,
        paid_total,
        received_at,
        issued_at,
        weight,
        price_list,
        service_price,
        wh_cell,
        amount_paid_cash,
        amount_paid_cashless,
        amount_paid_bonus,
        amount_deposited,
        photo_add,
        postpone_button,
        cancel_button,
        common_debt,
        client_debt_in_dp
    }
}

export const kartaDostupnostiElementovKartochkiZakaza = {
    [Roli.Name.Admin]: availabilityMap(
        true,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        true,
        false,
        true,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
    ),
    [Roli.Name.Manager]: availabilityMap(
        true,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
        true,
        false,
        true,
        available_for_admin_or_manager,
        available_for_admin_or_manager,
    ),
    [Roli.Name.Courier]: availabilityMap(
        true,
        false,
        false,
        isReceived,
        false,
        false,
        isReceived,
        false,
        false,
        false,
        isReceived,
        false,
        isReceived,
        isReceived,
        isReceived,
        isReceived,
        true,
        false,
        true,
        false
    ),
    [Roli.Name.Storekeeper]: availabilityMap(
        true,
        available_for_storekeeper,
        false,
        available_for_storekeeper,
        false,
        false,
        true,
        available_for_storekeeper,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        available_for_storekeeper,
    ),
    [Roli.Name.Operator]: availabilityMap(
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
    ),
    [Roli.Name.Customer]: availabilityMap(
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
    ),
};